### ISSUE TITLE
What to do after the initial deployment

### ISSUE THREAD

**Issue by laurpaik-zz** [ga-wdi-boston/ember-deployment-guide#16]
When we update our app, should we be rebasing gh-pages off of master every time we deploy?

**Comment by raq929** [comment]
If it were me, I would delete the branch and go through the steps again. I don't think rebasing will get you the result you want.

**Comment by laurpaik-zz** [comment]
Okay, good to know. Bernard and I ended up deleting the gh-pages branch on Friday and went through it again, but I wasn't sure if that was a hack-ey solution or not

**Comment by payne-chris-r** [comment]
Yeah gh-pages is gross. I go with the `nuke_pave` approach as well...

**Comment by jrhorn424** [comment]
Please don't backtick "nuke & pave". It makes it sound like a task that ships with the Ember template.

**Comment by zchenbonterra** [comment]
Lauren told me about this. SO basically, I did not delete the gh-pages branch and it is working for me. Here are the steps that I did. Please let me know if I am wrong and if I should delete gh-pages every time since I follow the guide.
1. Checkout to gh-pages 
2. git merge master
3. add # to /dist inside .gitignore if needed***
4. git add and commit
5. ember build --environment=production
6. git add and commit
7. git subtree push --prefix dist origin gh-pages
8. checkout to master
